version: '3'
services:
  python3:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name:
      'python3'
    ports:
      - "8000:8000"
    working_dir:
      '/root/'
    tty:
      true
    volumes:
      - ./src:/root/src/
      - ~/.zshrc:/root/.zshrc

#version: '3'
#services:
#  python3.8:
#    container_name: python3.8
#    build:
#      context: .
#      dockerfile: Dockerfile
#    tty:
#      true
#    stdin_open:
#      true
#    deploy:
#      replicas: 1
#    volumes:
#      - ../src
#
