name: sample
on: [push, pull_request]
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello github acitons
      - run: echo ${{ github.event_name }} is event name
      - run: echo ${{ github.run_id }} is github.run_id
      - run: echo ${{ job.status }} is job.status

